drop extension if exists "pg_net";

create type "public"."papel_usuario" as enum ('admin', 'gestor', 'operador', 'tecnico', 'analista');

create type "public"."prioridade_chamado" as enum ('baixa', 'media', 'alta', 'critica');

create type "public"."status_chamado" as enum ('aberto', 'atribuido', 'em_atendimento', 'pendente', 'finalizado', 'cancelado');

drop policy "solicitacoes_acesso_insert_publico" on "public"."solicitacoes_acesso";

revoke delete on table "public"."aceites_legais" from "anon";

revoke select on table "public"."aceites_legais" from "anon";

revoke update on table "public"."aceites_legais" from "anon";

revoke delete on table "public"."aceites_legais" from "authenticated";

revoke insert on table "public"."aceites_legais" from "authenticated";

revoke update on table "public"."aceites_legais" from "authenticated";

revoke delete on table "public"."aceites_legais" from "service_role";

revoke insert on table "public"."aceites_legais" from "service_role";

revoke delete on table "public"."solicitacoes_acesso" from "anon";

revoke select on table "public"."solicitacoes_acesso" from "anon";

revoke update on table "public"."solicitacoes_acesso" from "anon";

revoke delete on table "public"."solicitacoes_acesso" from "authenticated";

revoke insert on table "public"."solicitacoes_acesso" from "authenticated";

revoke delete on table "public"."solicitacoes_acesso" from "service_role";

revoke insert on table "public"."solicitacoes_acesso" from "service_role";

alter table "public"."solicitacoes_acesso" drop constraint "solicitacoes_acesso_status_provisionamento_check";

alter table "public"."solicitacoes_acesso" drop constraint "solicitacoes_acesso_status_check";

drop function if exists "public"."calcular_expiracao_horas_uteis"(inicio timestamp with time zone, horas_uteis integer);

drop index if exists "public"."solicitacoes_acesso_expira_em_idx";

drop index if exists "public"."solicitacoes_acesso_email_pendente_idx";


  create table "public"."chamados" (
    "id" uuid not null default gen_random_uuid(),
    "numero" bigint generated by default as identity not null,
    "cliente_id" uuid not null,
    "loja_id" uuid not null,
    "operador_id" uuid not null,
    "tecnico_id" uuid,
    "titulo" text not null,
    "descricao_problema" text,
    "status" text not null default 'pendente_agendamento'::text,
    "prioridade" public.prioridade_chamado not null default 'media'::public.prioridade_chamado,
    "aberto_em" timestamp with time zone not null default now(),
    "atendimento_iniciado_em" timestamp with time zone,
    "finalizado_em" timestamp with time zone,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "tipo_chamado" text,
    "impacto" text,
    "urgencia" text,
    "origem" text,
    "ativo_afetado" text,
    "analista_responsavel_id" uuid,
    "tecnico_responsavel_id" uuid,
    "categoria" text,
    "ativo_tipo" text,
    "ativo_descricao" text,
    "marca" text,
    "modelo" text
      );


alter table "public"."chamados" enable row level security;


  create table "public"."clientes" (
    "id" uuid not null default gen_random_uuid(),
    "nome_fantasia" text not null,
    "razao_social" text,
    "cnpj" text,
    "email_contato" text,
    "telefone" text,
    "ativo" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."clientes" enable row level security;


  create table "public"."evidencias_anexos" (
    "id" uuid not null default gen_random_uuid(),
    "chamado_id" uuid not null,
    "usuario_id" uuid not null,
    "arquivo_url" text not null,
    "tipo_arquivo" text,
    "legenda" text,
    "enviado_em" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."evidencias_anexos" enable row level security;


  create table "public"."historico_status" (
    "id" uuid not null default gen_random_uuid(),
    "chamado_id" uuid not null,
    "usuario_id" uuid not null,
    "status_anterior" text,
    "status_novo" text not null,
    "observacao" text,
    "alterado_em" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."historico_status" enable row level security;


  create table "public"."lojas" (
    "id" uuid not null default gen_random_uuid(),
    "cliente_id" uuid not null,
    "nome_loja" text not null,
    "codigo_interno" text,
    "endereco" text,
    "cidade" text,
    "estado" text default 'CE'::text,
    "contato_local" text,
    "telefone" text,
    "ativo" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."lojas" enable row level security;


  create table "public"."perfis" (
    "id" uuid not null,
    "nome_completo" text not null,
    "email" text,
    "telefone" text,
    "papel" public.papel_usuario not null default 'tecnico'::public.papel_usuario,
    "ativo" boolean not null default true,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."perfis" enable row level security;


  create table "public"."registros_tecnicos" (
    "id" uuid not null default gen_random_uuid(),
    "chamado_id" uuid not null,
    "tecnico_id" uuid not null,
    "problema_identificado" text,
    "testes_feitos" text,
    "solucao" text,
    "observacoes_internas" text,
    "registrado_em" timestamp with time zone not null default now(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "public"."registros_tecnicos" enable row level security;

alter table "public"."solicitacoes_acesso" drop column "convite_reenviado_em";

alter table "public"."solicitacoes_acesso" drop column "expira_em";

alter table "public"."solicitacoes_acesso" drop column "motivo_rejeicao";

alter table "public"."solicitacoes_acesso" drop column "provisionamento_tentado_em";

alter table "public"."solicitacoes_acesso" drop column "status_provisionamento";

alter table "public"."solicitacoes_acesso" alter column "status" set default 'pendente_aprovacao'::text;

CREATE UNIQUE INDEX chamados_numero_key ON public.chamados USING btree (numero);

CREATE UNIQUE INDEX chamados_pkey ON public.chamados USING btree (id);

CREATE UNIQUE INDEX clientes_cnpj_key ON public.clientes USING btree (cnpj);

CREATE UNIQUE INDEX clientes_pkey ON public.clientes USING btree (id);

CREATE UNIQUE INDEX evidencias_anexos_pkey ON public.evidencias_anexos USING btree (id);

CREATE UNIQUE INDEX historico_status_pkey ON public.historico_status USING btree (id);

CREATE INDEX idx_chamados_cliente_id ON public.chamados USING btree (cliente_id);

CREATE INDEX idx_chamados_loja_id ON public.chamados USING btree (loja_id);

CREATE INDEX idx_chamados_status ON public.chamados USING btree (status);

CREATE INDEX idx_chamados_tecnico_id ON public.chamados USING btree (tecnico_id);

CREATE INDEX idx_evidencias_chamado_id ON public.evidencias_anexos USING btree (chamado_id);

CREATE INDEX idx_historico_chamado_id ON public.historico_status USING btree (chamado_id);

CREATE INDEX idx_lojas_cliente_id ON public.lojas USING btree (cliente_id);

CREATE INDEX idx_registros_chamado_id ON public.registros_tecnicos USING btree (chamado_id);

CREATE UNIQUE INDEX lojas_pkey ON public.lojas USING btree (id);

CREATE UNIQUE INDEX perfis_pkey ON public.perfis USING btree (id);

CREATE UNIQUE INDEX registros_tecnicos_pkey ON public.registros_tecnicos USING btree (id);

CREATE UNIQUE INDEX solicitacoes_acesso_email_pendente_idx ON public.solicitacoes_acesso USING btree (lower(email)) WHERE (status = 'pendente_aprovacao'::text);

alter table "public"."chamados" add constraint "chamados_pkey" PRIMARY KEY using index "chamados_pkey";

alter table "public"."clientes" add constraint "clientes_pkey" PRIMARY KEY using index "clientes_pkey";

alter table "public"."evidencias_anexos" add constraint "evidencias_anexos_pkey" PRIMARY KEY using index "evidencias_anexos_pkey";

alter table "public"."historico_status" add constraint "historico_status_pkey" PRIMARY KEY using index "historico_status_pkey";

alter table "public"."lojas" add constraint "lojas_pkey" PRIMARY KEY using index "lojas_pkey";

alter table "public"."perfis" add constraint "perfis_pkey" PRIMARY KEY using index "perfis_pkey";

alter table "public"."registros_tecnicos" add constraint "registros_tecnicos_pkey" PRIMARY KEY using index "registros_tecnicos_pkey";

alter table "public"."aceites_legais" add constraint "aceites_legais_perfil_id_fkey" FOREIGN KEY (perfil_id) REFERENCES public.perfis(id) not valid;

alter table "public"."aceites_legais" validate constraint "aceites_legais_perfil_id_fkey";

alter table "public"."chamados" add constraint "chamados_categoria_check" CHECK (((categoria IS NULL) OR (categoria = ANY (ARRAY['cabeamento'::text, 'cftv'::text, 'desktops'::text, 'pdvs'::text, 'automacao'::text, 'atendimento_interno'::text, 'impressoras_termicas'::text, 'impressoras'::text])))) not valid;

alter table "public"."chamados" validate constraint "chamados_categoria_check";

alter table "public"."chamados" add constraint "chamados_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) not valid;

alter table "public"."chamados" validate constraint "chamados_cliente_id_fkey";

alter table "public"."chamados" add constraint "chamados_loja_id_fkey" FOREIGN KEY (loja_id) REFERENCES public.lojas(id) not valid;

alter table "public"."chamados" validate constraint "chamados_loja_id_fkey";

alter table "public"."chamados" add constraint "chamados_numero_key" UNIQUE using index "chamados_numero_key";

alter table "public"."chamados" add constraint "chamados_operador_id_fkey" FOREIGN KEY (operador_id) REFERENCES public.perfis(id) not valid;

alter table "public"."chamados" validate constraint "chamados_operador_id_fkey";

alter table "public"."chamados" add constraint "chamados_status_check" CHECK ((status = ANY (ARRAY['pendente_agendamento'::text, 'orcamento'::text, 'agendado'::text, 'em_atendimento'::text, 'pendente_peca'::text, 'resolvido'::text, 'faturado'::text]))) not valid;

alter table "public"."chamados" validate constraint "chamados_status_check";

alter table "public"."chamados" add constraint "chamados_tecnico_id_fkey" FOREIGN KEY (tecnico_id) REFERENCES public.perfis(id) not valid;

alter table "public"."chamados" validate constraint "chamados_tecnico_id_fkey";

alter table "public"."clientes" add constraint "clientes_cnpj_key" UNIQUE using index "clientes_cnpj_key";

alter table "public"."evidencias_anexos" add constraint "evidencias_anexos_chamado_id_fkey" FOREIGN KEY (chamado_id) REFERENCES public.chamados(id) not valid;

alter table "public"."evidencias_anexos" validate constraint "evidencias_anexos_chamado_id_fkey";

alter table "public"."evidencias_anexos" add constraint "evidencias_anexos_usuario_id_fkey" FOREIGN KEY (usuario_id) REFERENCES public.perfis(id) not valid;

alter table "public"."evidencias_anexos" validate constraint "evidencias_anexos_usuario_id_fkey";

alter table "public"."historico_status" add constraint "historico_status_chamado_id_fkey" FOREIGN KEY (chamado_id) REFERENCES public.chamados(id) not valid;

alter table "public"."historico_status" validate constraint "historico_status_chamado_id_fkey";

alter table "public"."historico_status" add constraint "historico_status_status_anterior_check" CHECK (((status_anterior IS NULL) OR (status_anterior = ANY (ARRAY['pendente_agendamento'::text, 'orcamento'::text, 'agendado'::text, 'em_atendimento'::text, 'pendente_peca'::text, 'resolvido'::text, 'faturado'::text])))) not valid;

alter table "public"."historico_status" validate constraint "historico_status_status_anterior_check";

alter table "public"."historico_status" add constraint "historico_status_status_novo_check" CHECK ((status_novo = ANY (ARRAY['pendente_agendamento'::text, 'orcamento'::text, 'agendado'::text, 'em_atendimento'::text, 'pendente_peca'::text, 'resolvido'::text, 'faturado'::text]))) not valid;

alter table "public"."historico_status" validate constraint "historico_status_status_novo_check";

alter table "public"."historico_status" add constraint "historico_status_usuario_id_fkey" FOREIGN KEY (usuario_id) REFERENCES public.perfis(id) not valid;

alter table "public"."historico_status" validate constraint "historico_status_usuario_id_fkey";

alter table "public"."lojas" add constraint "lojas_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) not valid;

alter table "public"."lojas" validate constraint "lojas_cliente_id_fkey";

alter table "public"."perfis" add constraint "perfis_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."perfis" validate constraint "perfis_id_fkey";

alter table "public"."registros_tecnicos" add constraint "registros_tecnicos_chamado_id_fkey" FOREIGN KEY (chamado_id) REFERENCES public.chamados(id) not valid;

alter table "public"."registros_tecnicos" validate constraint "registros_tecnicos_chamado_id_fkey";

alter table "public"."registros_tecnicos" add constraint "registros_tecnicos_tecnico_id_fkey" FOREIGN KEY (tecnico_id) REFERENCES public.perfis(id) not valid;

alter table "public"."registros_tecnicos" validate constraint "registros_tecnicos_tecnico_id_fkey";

alter table "public"."solicitacoes_acesso" add constraint "solicitacoes_acesso_aprovado_por_fkey" FOREIGN KEY (aprovado_por) REFERENCES public.perfis(id) not valid;

alter table "public"."solicitacoes_acesso" validate constraint "solicitacoes_acesso_aprovado_por_fkey";

alter table "public"."solicitacoes_acesso" add constraint "solicitacoes_acesso_perfil_id_fkey" FOREIGN KEY (perfil_id) REFERENCES public.perfis(id) not valid;

alter table "public"."solicitacoes_acesso" validate constraint "solicitacoes_acesso_perfil_id_fkey";

alter table "public"."solicitacoes_acesso" add constraint "solicitacoes_acesso_rejeitado_por_fkey" FOREIGN KEY (rejeitado_por) REFERENCES public.perfis(id) not valid;

alter table "public"."solicitacoes_acesso" validate constraint "solicitacoes_acesso_rejeitado_por_fkey";

alter table "public"."solicitacoes_acesso" add constraint "solicitacoes_acesso_status_check" CHECK ((status = ANY (ARRAY['pendente_aprovacao'::text, 'aprovado'::text, 'rejeitado'::text, 'cancelado'::text]))) not valid;

alter table "public"."solicitacoes_acesso" validate constraint "solicitacoes_acesso_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.atualizar_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.usuario_admin_ou_gestor_ativo()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.perfis
    where id = auth.uid()
      and ativo = true
      and papel in ('admin', 'gestor')
  );
$function$
;

CREATE OR REPLACE FUNCTION public.usuario_operacional_ativo()
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1
    from public.perfis
    where id = auth.uid()
      and ativo = true
      and papel in ('admin', 'gestor', 'operador', 'analista', 'tecnico')
  );
$function$
;

grant insert on table "public"."chamados" to "anon";

grant references on table "public"."chamados" to "anon";

grant select on table "public"."chamados" to "anon";

grant trigger on table "public"."chamados" to "anon";

grant truncate on table "public"."chamados" to "anon";

grant update on table "public"."chamados" to "anon";

grant insert on table "public"."chamados" to "authenticated";

grant references on table "public"."chamados" to "authenticated";

grant select on table "public"."chamados" to "authenticated";

grant trigger on table "public"."chamados" to "authenticated";

grant truncate on table "public"."chamados" to "authenticated";

grant update on table "public"."chamados" to "authenticated";

grant references on table "public"."chamados" to "service_role";

grant trigger on table "public"."chamados" to "service_role";

grant truncate on table "public"."chamados" to "service_role";

grant references on table "public"."clientes" to "anon";

grant select on table "public"."clientes" to "anon";

grant trigger on table "public"."clientes" to "anon";

grant truncate on table "public"."clientes" to "anon";

grant references on table "public"."clientes" to "authenticated";

grant select on table "public"."clientes" to "authenticated";

grant trigger on table "public"."clientes" to "authenticated";

grant truncate on table "public"."clientes" to "authenticated";

grant references on table "public"."clientes" to "service_role";

grant trigger on table "public"."clientes" to "service_role";

grant truncate on table "public"."clientes" to "service_role";

grant references on table "public"."evidencias_anexos" to "anon";

grant select on table "public"."evidencias_anexos" to "anon";

grant trigger on table "public"."evidencias_anexos" to "anon";

grant truncate on table "public"."evidencias_anexos" to "anon";

grant insert on table "public"."evidencias_anexos" to "authenticated";

grant references on table "public"."evidencias_anexos" to "authenticated";

grant select on table "public"."evidencias_anexos" to "authenticated";

grant trigger on table "public"."evidencias_anexos" to "authenticated";

grant truncate on table "public"."evidencias_anexos" to "authenticated";

grant update on table "public"."evidencias_anexos" to "authenticated";

grant references on table "public"."evidencias_anexos" to "service_role";

grant trigger on table "public"."evidencias_anexos" to "service_role";

grant truncate on table "public"."evidencias_anexos" to "service_role";

grant insert on table "public"."historico_status" to "anon";

grant references on table "public"."historico_status" to "anon";

grant select on table "public"."historico_status" to "anon";

grant trigger on table "public"."historico_status" to "anon";

grant truncate on table "public"."historico_status" to "anon";

grant insert on table "public"."historico_status" to "authenticated";

grant references on table "public"."historico_status" to "authenticated";

grant select on table "public"."historico_status" to "authenticated";

grant trigger on table "public"."historico_status" to "authenticated";

grant truncate on table "public"."historico_status" to "authenticated";

grant references on table "public"."historico_status" to "service_role";

grant trigger on table "public"."historico_status" to "service_role";

grant truncate on table "public"."historico_status" to "service_role";

grant references on table "public"."lojas" to "anon";

grant select on table "public"."lojas" to "anon";

grant trigger on table "public"."lojas" to "anon";

grant truncate on table "public"."lojas" to "anon";

grant references on table "public"."lojas" to "authenticated";

grant select on table "public"."lojas" to "authenticated";

grant trigger on table "public"."lojas" to "authenticated";

grant truncate on table "public"."lojas" to "authenticated";

grant references on table "public"."lojas" to "service_role";

grant trigger on table "public"."lojas" to "service_role";

grant truncate on table "public"."lojas" to "service_role";

grant references on table "public"."perfis" to "anon";

grant trigger on table "public"."perfis" to "anon";

grant truncate on table "public"."perfis" to "anon";

grant references on table "public"."perfis" to "authenticated";

grant select on table "public"."perfis" to "authenticated";

grant trigger on table "public"."perfis" to "authenticated";

grant truncate on table "public"."perfis" to "authenticated";

grant insert on table "public"."perfis" to "service_role";

grant references on table "public"."perfis" to "service_role";

grant select on table "public"."perfis" to "service_role";

grant trigger on table "public"."perfis" to "service_role";

grant truncate on table "public"."perfis" to "service_role";

grant update on table "public"."perfis" to "service_role";

grant insert on table "public"."registros_tecnicos" to "anon";

grant references on table "public"."registros_tecnicos" to "anon";

grant select on table "public"."registros_tecnicos" to "anon";

grant trigger on table "public"."registros_tecnicos" to "anon";

grant truncate on table "public"."registros_tecnicos" to "anon";

grant insert on table "public"."registros_tecnicos" to "authenticated";

grant references on table "public"."registros_tecnicos" to "authenticated";

grant select on table "public"."registros_tecnicos" to "authenticated";

grant trigger on table "public"."registros_tecnicos" to "authenticated";

grant truncate on table "public"."registros_tecnicos" to "authenticated";

grant references on table "public"."registros_tecnicos" to "service_role";

grant trigger on table "public"."registros_tecnicos" to "service_role";

grant truncate on table "public"."registros_tecnicos" to "service_role";


  create policy "aceites_legais_select_admin_gestor"
  on "public"."aceites_legais"
  as permissive
  for select
  to authenticated
using (public.usuario_admin_ou_gestor_ativo());



  create policy "chamados_insert_operacionais"
  on "public"."chamados"
  as permissive
  for insert
  to authenticated
with check ((public.usuario_operacional_ativo() AND (operador_id = auth.uid())));



  create policy "chamados_select_operacionais"
  on "public"."chamados"
  as permissive
  for select
  to authenticated
using (public.usuario_operacional_ativo());



  create policy "chamados_update_operacionais"
  on "public"."chamados"
  as permissive
  for update
  to authenticated
using (public.usuario_operacional_ativo())
with check (public.usuario_operacional_ativo());



  create policy "dev_insert_chamados"
  on "public"."chamados"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "dev_select_chamados"
  on "public"."chamados"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "dev_update_chamados"
  on "public"."chamados"
  as permissive
  for update
  to anon, authenticated
using (true)
with check (true);



  create policy "clientes_select_operacionais"
  on "public"."clientes"
  as permissive
  for select
  to authenticated
using (public.usuario_operacional_ativo());



  create policy "dev_select_clientes"
  on "public"."clientes"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "dev_select_evidencias_anexos"
  on "public"."evidencias_anexos"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "evidencias_anexos_insert_autenticados"
  on "public"."evidencias_anexos"
  as permissive
  for insert
  to authenticated
with check (((auth.uid() IS NOT NULL) AND (usuario_id = auth.uid())));



  create policy "evidencias_anexos_select_autenticados"
  on "public"."evidencias_anexos"
  as permissive
  for select
  to authenticated
using ((auth.uid() IS NOT NULL));



  create policy "evidencias_anexos_update_autenticados"
  on "public"."evidencias_anexos"
  as permissive
  for update
  to authenticated
using (((auth.uid() IS NOT NULL) AND (usuario_id = auth.uid())))
with check (((auth.uid() IS NOT NULL) AND (usuario_id = auth.uid())));



  create policy "dev_insert_historico_status"
  on "public"."historico_status"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "dev_select_historico_status"
  on "public"."historico_status"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "historico_status_insert_operacionais"
  on "public"."historico_status"
  as permissive
  for insert
  to authenticated
with check ((public.usuario_operacional_ativo() AND (usuario_id = auth.uid())));



  create policy "historico_status_select_operacionais"
  on "public"."historico_status"
  as permissive
  for select
  to authenticated
using (public.usuario_operacional_ativo());



  create policy "dev_select_lojas"
  on "public"."lojas"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "lojas_select_operacionais"
  on "public"."lojas"
  as permissive
  for select
  to authenticated
using (public.usuario_operacional_ativo());



  create policy "perfis_select_operacionais"
  on "public"."perfis"
  as permissive
  for select
  to authenticated
using (((id = auth.uid()) OR public.usuario_operacional_ativo()));



  create policy "dev_insert_registros_tecnicos"
  on "public"."registros_tecnicos"
  as permissive
  for insert
  to anon, authenticated
with check (true);



  create policy "dev_select_registros_tecnicos"
  on "public"."registros_tecnicos"
  as permissive
  for select
  to anon, authenticated
using (true);



  create policy "registros_tecnicos_insert_operacionais"
  on "public"."registros_tecnicos"
  as permissive
  for insert
  to authenticated
with check ((public.usuario_operacional_ativo() AND (tecnico_id = auth.uid())));



  create policy "registros_tecnicos_select_operacionais"
  on "public"."registros_tecnicos"
  as permissive
  for select
  to authenticated
using (public.usuario_operacional_ativo());



  create policy "solicitacoes_acesso_select_admin_gestor"
  on "public"."solicitacoes_acesso"
  as permissive
  for select
  to authenticated
using (public.usuario_admin_ou_gestor_ativo());



  create policy "solicitacoes_acesso_update_admin_gestor"
  on "public"."solicitacoes_acesso"
  as permissive
  for update
  to authenticated
using (public.usuario_admin_ou_gestor_ativo())
with check ((public.usuario_admin_ou_gestor_ativo() AND (status = ANY (ARRAY['pendente_aprovacao'::text, 'aprovado'::text, 'rejeitado'::text, 'cancelado'::text]))));



  create policy "solicitacoes_acesso_insert_publico"
  on "public"."solicitacoes_acesso"
  as permissive
  for insert
  to anon
with check (((status = 'pendente_aprovacao'::text) AND (aceite_termos = true) AND (aceite_privacidade = true) AND (nome_completo <> ''::text) AND (email <> ''::text) AND (empresa <> ''::text)));


CREATE TRIGGER trg_chamados_updated_at BEFORE UPDATE ON public.chamados FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();

CREATE TRIGGER trg_clientes_updated_at BEFORE UPDATE ON public.clientes FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();

CREATE TRIGGER trg_lojas_updated_at BEFORE UPDATE ON public.lojas FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();

CREATE TRIGGER trg_perfis_updated_at BEFORE UPDATE ON public.perfis FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();

CREATE TRIGGER trg_registros_tecnicos_updated_at BEFORE UPDATE ON public.registros_tecnicos FOR EACH ROW EXECUTE FUNCTION public.atualizar_updated_at();


